FROM php:8.4-cli-alpine

RUN apk add --no-cache freetype-dev libjpeg-turbo-dev libpng-dev libwebp-dev $PHPIZE_DEPS && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && docker-php-ext-install -j$(nproc) gd pcntl pdo_mysql && pecl install redis && docker-php-ext-enable redis && apk del $PHPIZE_DEPS

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader && mkdir -p storage/app/private storage/app/public storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs

CMD ["php", "artisan", "horizon"]
